# Generated by Django 2.0.1 on 2018-04-13 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccessPoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac', models.CharField(max_length=200, verbose_name='Mac')),
                ('bssid', models.CharField(max_length=200, verbose_name='BSSID')),
                ('bandwidth', models.CharField(max_length=200, verbose_name='Largura da Banda')),
                ('standard', models.CharField(max_length=200, verbose_name='Padrão')),
                ('channel', models.IntegerField(default=6, verbose_name='Canal')),
                ('frequency', models.IntegerField(verbose_name='Frequencia')),
                ('signal', models.CharField(max_length=200, verbose_name='Sinal')),
            ],
        ),
    ]
