# Generated by Django 2.0.1 on 2018-02-01 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('anomalias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assinatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.CharField(max_length=200, verbose_name='Descrição')),
                ('assinatura', models.CharField(max_length=200, verbose_name='Assinatura')),
                ('ativo', models.IntegerField(default=1, verbose_name='Ativo')),
                ('data_cad', models.DateTimeField(auto_now_add=True, verbose_name='Data de Cadastro')),
                ('id_anomalia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anomalias.Anomalia')),
            ],
        ),
    ]
