# Generated by Django 2.0.1 on 2018-05-01 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Descricao')),
                ('file', models.TextField(max_length=200, verbose_name='Arquivo')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
                ('priority', models.CharField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10)], default='5', max_length=6, verbose_name='Prioridade')),
            ],
        ),
    ]
