# Generated by Django 2.0.1 on 2018-04-16 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Descricao')),
                ('file', models.TextField(max_length=200, verbose_name='Arquivo')),
                ('status', models.IntegerField(default=0, verbose_name='Status')),
            ],
        ),
    ]
