# Generated by Django 2.0.1 on 2018-02-01 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anomalia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.TextField(max_length=200, verbose_name='Descrição')),
                ('identificador', models.TextField(max_length=200, verbose_name='Identificador')),
                ('ativo', models.IntegerField(default=1, verbose_name='Ativo')),
                ('prioridade', models.IntegerField(default=1, verbose_name='Prioridade')),
            ],
        ),
    ]
