# Generated by Django 2.0.1 on 2018-04-10 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200, verbose_name='Descrição')),
                ('datetime', models.DateTimeField(auto_now_add=True, verbose_name='Data Hora')),
            ],
        ),
    ]
